### ISSUE TITLE
How to connect a weather station with azure IoT-Hub via pnp Bridge

### ISSUE THREAD

**Issue by TJ-404** [Azure/iot-plug-and-play-bridge#53]
Hello,

for the last few days I was wondering if I can connect a weather station off the shelf with the Azure IoT-Hub. 
I don't really want to hard code the connection. 
So is it possible to connect a weather station which is not programmable with a Plug and Play Bridge?
Or is there another way to get the data into the IoT-Hub.

The weather station can be connected via Wi-Fi to the internet. 

As you can see I dont really konw much in this area, so some help would be really good. 

Thank you very much.

**Comment by usivagna** [comment]
Hi @TJ-404 , 

Thank you for following-up with an issue on GitHub! Do you have a datasheet or documentation on your weather station? Those  details will help us answer your specific question. 

In general, the process to connect a brownfield/existing non-programmable device like yours via IoT Plug and Play bridge is as follows: 

1. Create a [Digital Twins Definition Language (DTDL) model](https://github.com/Azure/opendigitaltwins-dtdl) to describe your device. To learn more, see [Understand components in IoT Plug and Play models](https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-components).
2. Determine the protocol your device uses to  connect to the gateway running IoT Plug and Play bridge:
- If your protocol is already supported by IoT Plug and Play bridge, you can follow the instructions for that protocol adapter, [see supported protocols](https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-iot-pnp-bridge#supported-protocols-and-sensors)
- If the protocol your device uses is not supported yet, you can either write your own adapter, see  documentation [Extend the IoT Plug and Play bridge](https://docs.microsoft.com/en-us/azure/iot-pnp/howto-author-pnp-bridge-adapter). Alternatively, you can [file a feature request](https://github.com/Azure/iot-plug-and-play-bridge/issues) and one of our community members may be able to assist. 
3.  Once you decide on a adapter (either an existing, or one you  have built), simply run and configure the bridge to connect your device to an IoT hub or IoT Central., see [How to build, and deploy the bridge](https://docs.microsoft.com/en-us/azure/iot-pnp/howto-build-deploy-extend-pnp-bridge)

Hope that helps, and if you have more specific details happy to answer any questions specific to your situation. Thanks!

**Comment by usivagna** [comment]
Closing this issue, please re-open if you have more information.
